import type { PlayerProjection, LeagueSettings, ScoringFormat, ValueCalculationSettings } from '@shared/schema';

export const SAMPLE_LEAGUE_SETTINGS: LeagueSettings = {
  leagueName: 'Sample League',
  teamCount: 12,
  auctionBudget: 260,
  totalRosterSpots: 23,
  positionRequirements: {
    C: 1,
    '1B': 1,
    '2B': 1,
    '3B': 1,
    SS: 1,
    OF: 3,
    UTIL: 1,
    MI: 1,
    CI: 1,
    SP: 5,
    RP: 2,
    P: 0,
    BENCH: 5,
  },
};

export const SAMPLE_SCORING_FORMAT: ScoringFormat = {
  type: 'roto',
  hittingCategories: ['R', 'HR', 'RBI', 'SB', 'AVG'],
  pitchingCategories: ['W', 'SV', 'K', 'ERA', 'WHIP'],
};

export const SAMPLE_VALUE_SETTINGS: ValueCalculationSettings = {
  method: 'sgp',
  replacementLevelMethod: 'lastDrafted',
  applyPositionScarcity: true,
  hitterBudgetPercent: 65,
  hitterPitcherSplit: { method: 'calculated' },
  showTiers: true,
};

export const SAMPLE_PROJECTIONS: PlayerProjection[] = [
  { name: 'Ronald Acuna Jr.', team: 'ATL', positions: ['OF'], stats: { R: 120, HR: 35, RBI: 95, SB: 55, AVG: 0.287 } },
  { name: 'Mookie Betts', team: 'LAD', positions: ['OF', '2B', 'SS'], stats: { R: 115, HR: 32, RBI: 90, SB: 15, AVG: 0.295 } },
  { name: 'Shohei Ohtani', team: 'LAD', positions: ['DH'], stats: { R: 100, HR: 50, RBI: 110, SB: 15, AVG: 0.295 } },
  { name: 'Freddie Freeman', team: 'LAD', positions: ['1B'], stats: { R: 105, HR: 28, RBI: 100, SB: 8, AVG: 0.305 } },
  { name: 'Corey Seager', team: 'TEX', positions: ['SS'], stats: { R: 95, HR: 32, RBI: 100, SB: 3, AVG: 0.285 } },
  { name: 'Trea Turner', team: 'PHI', positions: ['SS'], stats: { R: 100, HR: 25, RBI: 85, SB: 30, AVG: 0.285 } },
  { name: 'Marcus Semien', team: 'TEX', positions: ['2B'], stats: { R: 95, HR: 25, RBI: 85, SB: 15, AVG: 0.275 } },
  { name: 'Rafael Devers', team: 'BOS', positions: ['3B'], stats: { R: 95, HR: 30, RBI: 110, SB: 2, AVG: 0.280 } },
  { name: 'J.T. Realmuto', team: 'PHI', positions: ['C'], stats: { R: 70, HR: 22, RBI: 80, SB: 12, AVG: 0.265 } },
  { name: 'William Contreras', team: 'MIL', positions: ['C'], stats: { R: 75, HR: 20, RBI: 75, SB: 2, AVG: 0.275 } },
  { name: 'Juan Soto', team: 'NYY', positions: ['OF'], stats: { R: 100, HR: 35, RBI: 105, SB: 5, AVG: 0.285 } },
  { name: 'Yordan Alvarez', team: 'HOU', positions: ['DH', 'OF'], stats: { R: 90, HR: 40, RBI: 110, SB: 1, AVG: 0.295 } },
  { name: 'Mike Trout', team: 'LAA', positions: ['OF'], stats: { R: 85, HR: 35, RBI: 85, SB: 5, AVG: 0.280 } },
  { name: 'Julio Rodriguez', team: 'SEA', positions: ['OF'], stats: { R: 95, HR: 28, RBI: 90, SB: 25, AVG: 0.275 } },
  { name: 'Gunnar Henderson', team: 'BAL', positions: ['SS', '3B'], stats: { R: 100, HR: 30, RBI: 95, SB: 12, AVG: 0.270 } },
  { name: 'Bobby Witt Jr.', team: 'KC', positions: ['SS'], stats: { R: 105, HR: 28, RBI: 95, SB: 30, AVG: 0.290 } },
  { name: 'Matt Olson', team: 'ATL', positions: ['1B'], stats: { R: 95, HR: 40, RBI: 115, SB: 1, AVG: 0.255 } },
  { name: 'Vladimir Guerrero Jr.', team: 'TOR', positions: ['1B'], stats: { R: 85, HR: 32, RBI: 100, SB: 3, AVG: 0.285 } },
  { name: 'Jose Ramirez', team: 'CLE', positions: ['3B'], stats: { R: 95, HR: 25, RBI: 100, SB: 25, AVG: 0.280 } },
  { name: 'Austin Riley', team: 'ATL', positions: ['3B'], stats: { R: 85, HR: 35, RBI: 100, SB: 2, AVG: 0.270 } },
  { name: 'Gerrit Cole', team: 'NYY', positions: ['SP'], stats: { W: 14, SV: 0, K: 220, ERA: 2.85, WHIP: 0.98 } },
  { name: 'Spencer Strider', team: 'ATL', positions: ['SP'], stats: { W: 12, SV: 0, K: 250, ERA: 3.10, WHIP: 1.02 } },
  { name: 'Zack Wheeler', team: 'PHI', positions: ['SP'], stats: { W: 13, SV: 0, K: 210, ERA: 3.05, WHIP: 1.00 } },
  { name: 'Corbin Burnes', team: 'BAL', positions: ['SP'], stats: { W: 12, SV: 0, K: 200, ERA: 3.15, WHIP: 1.05 } },
  { name: 'Tarik Skubal', team: 'DET', positions: ['SP'], stats: { W: 15, SV: 0, K: 220, ERA: 2.70, WHIP: 0.95 } },
  { name: 'Pablo Lopez', team: 'MIN', positions: ['SP'], stats: { W: 11, SV: 0, K: 180, ERA: 3.40, WHIP: 1.10 } },
  { name: 'Logan Webb', team: 'SF', positions: ['SP'], stats: { W: 12, SV: 0, K: 175, ERA: 3.25, WHIP: 1.08 } },
  { name: 'Cristopher Sanchez', team: 'PHI', positions: ['SP'], stats: { W: 10, SV: 0, K: 160, ERA: 3.50, WHIP: 1.15 } },
  { name: 'Emmanuel Clase', team: 'CLE', positions: ['RP'], stats: { W: 3, SV: 42, K: 75, ERA: 1.20, WHIP: 0.78 } },
  { name: 'Devin Williams', team: 'NYY', positions: ['RP'], stats: { W: 4, SV: 38, K: 95, ERA: 1.50, WHIP: 0.88 } },
  { name: 'Josh Hader', team: 'HOU', positions: ['RP'], stats: { W: 3, SV: 35, K: 85, ERA: 1.80, WHIP: 0.92 } },
  { name: 'Ryan Helsley', team: 'STL', positions: ['RP'], stats: { W: 4, SV: 40, K: 80, ERA: 1.60, WHIP: 0.85 } },
  { name: 'Edwin Diaz', team: 'NYM', positions: ['RP'], stats: { W: 3, SV: 32, K: 90, ERA: 2.00, WHIP: 0.90 } },
  { name: 'Elly De La Cruz', team: 'CIN', positions: ['SS'], stats: { R: 100, HR: 22, RBI: 70, SB: 60, AVG: 0.250 } },
  { name: 'Adley Rutschman', team: 'BAL', positions: ['C'], stats: { R: 75, HR: 22, RBI: 85, SB: 2, AVG: 0.275 } },
  { name: 'Bo Bichette', team: 'TOR', positions: ['SS'], stats: { R: 85, HR: 18, RBI: 75, SB: 10, AVG: 0.280 } },
  { name: 'Kyle Tucker', team: 'CHC', positions: ['OF'], stats: { R: 90, HR: 28, RBI: 95, SB: 15, AVG: 0.280 } },
  { name: 'Corbin Carroll', team: 'ARI', positions: ['OF'], stats: { R: 95, HR: 20, RBI: 70, SB: 35, AVG: 0.265 } },
  { name: 'Pete Alonso', team: 'NYM', positions: ['1B'], stats: { R: 80, HR: 40, RBI: 110, SB: 1, AVG: 0.245 } },
  { name: 'Bryce Harper', team: 'PHI', positions: ['1B', 'DH'], stats: { R: 85, HR: 30, RBI: 90, SB: 5, AVG: 0.280 } },
];
